// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrcyqjydunbqcdxedicr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyY3lxanlkdW5icWNkeGVkaWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzA5MzAsImV4cCI6MjA3MzUwNjkzMH0.V80oneVxfuzcUj0LGgOX7_m6FBqouZkVc1KhoV77jgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});